### ISSUE TITLE
Why all the changes

### ISSUE THREAD

**Issue by kscott5** [aspnet/cli-samples#10]
Now I'm reading that dnx is no longer supported. Why all the changes? What does RC1 really mean? 

This is not what I expect from from a so called production ready system or experienced software architects/developers. and

If you are trying to say I need to take my own medicine that's BS too. You know that this has occurred for more than two years now.

If its not ready then just say it. But stop giving me a hard time trying to prove that I can keep up.

JUST BS!!!!

**Comment by ctolkien** [comment]
https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/

**Comment by kscott5** [comment]
@ctolkien Well, there I have it! Lol! Frustration still there but the changes appear reasonable. Thanks for posting this link! Is there any news feeds your subscribe to that keeps you update to changes such as this?

Kvm-> DotNet -> Dnx -> Dotnet

**Comment by lszomoru** [comment]
@kscott5 I recommend that you watch the weekly community stand-ups: https://live.asp.net/

**Comment by ctolkien** [comment]
@kscott5 +1 on the weekly community stand-ups. They are invaluable in giving a frank discussion into the state of things.

**Comment by kscott5** [comment]
@lszomoru  and @ctolkien I have it on my calendar. Thanks again!!!!
