### ISSUE TITLE
Exception on dotnet run

### ISSUE THREAD

**Issue by tonysneed** [aspnet/cli-samples#13]
After installing the [latest](https://dotnet.github.io/getting-started/) PKG for OS X, I did a `dotnet restore` from the solution root, but there some errors.

```console
info :   GET https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/runtime.any.system.threading.tasks/4.0.11-rc3-23809/runtime.any.system.threading.tasks.4.0.11-rc3-23809.nupkg.
info :   NotFound https://api.nuget.org/v3-flatcontainer/runtime.any.system.runtime.interopservices/index.json 2103ms
```

When executing `dotnet run` for any of the apps, I then receive an exception.

```console
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'GlobalizationNative_IsNormalized' in DLL 'System.Globalization.Native'.
```

Any ideas what might be wrong? Thanks!

**Comment by moozzyk** [comment]
@glennc - is this the same you saw yesterday when you tried it?

**Comment by moozzyk** [comment]
I think it might be because of the `-rc3-` package which might be a result of https://github.com/aspnet/cli-samples/blob/master/NuGet.Config#L7-L8

I tried removing these feeds yesterday but there are problems with the cidev feed at the moment so was not able to verify this.

**Comment by tonysneed** [comment]
Thanks for looking into this. I take it the cidev feed is preferable to vnext, i.e., more aligned with the CLI samples?

**Comment by ellismg** [comment]
To enable some CoreRT scinerios we renamed some exports on System.Globalization.Native.  You'd see this error of the runtime and library were out of sync.  I'll look into it.

**Comment by tonysneed** [comment]
Here is what I get for `dotnet --version`:

```console
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by davidfowl** [comment]
Try changing the standard library reference to "NETStandard.Library": "1.0.0-rc2-23808"

**Comment by tonysneed** [comment]
Changed the standard library reference version in each package.json file, but I'm still getting the same exception.

**Comment by ellismg** [comment]
I looked into this some.  I think the changes we have been making in the `System.Globalization.Native.dylib` shim have pointed out an issue in the CLI.

As I mentioned earlier, we renamed the exports on `System.Globalization.Native.dylib` to be decorated with a prefix to prevent clashing if CoreRT ever wants to staticlly link the library into an application.

What's happening in this case is we are using a `System.Globalization.Extensions.dll` version that has the rename but the process has loaded a `System.Globalization.Native.dylib` without the rename.  While the version restored via `dotnet restore` was correct, the version in the `runtime` folder of the CLI itself is out of date.  It would appear that `dotnet run` is picking up that version of the runtime to run the application on.

Here's the start of the log for actually running the application when COREHOST_TRACE is set to 3

```
Running /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50/HelloMvc 
Process ID: 7327
Tracing enabled
dyld: loaded: /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50/libhostpolicy.dylib
Calling host entrypoint from library at own dir /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50
Tracing enabled
checking for CoreCLR in default location: /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50/libcoreclr.dylib
checking for CoreCLR in default location: /usr/share/dotnet/runtime/coreclr/libcoreclr.dylib
checking for CoreCLR in default location: /usr/local/share/dotnet/runtime/coreclr/libcoreclr.dylib
Package directory: /Users/matell/.nuget/packages
Adding files from dir /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50
Adding HelloMvc to local assembly set from /Users/matell/cli-samples/HelloMvc/bin/.dotnetrun/51792f7397934c049df9b76286bd5ee4/Debug/dnxcore50/HelloMvc.dll
Adding tpa entry: /usr/local/share/dotnet/runtime/coreclr/mscorlib.ni.dll
```

I set `DYLD_PRINT_LIBRARIES_POST_LAUNCH` to get some information from the native loaded about what libraries are loaded and I see the following:

```
dyld: loaded: /usr/local/share/dotnet/runtime/coreclr/libcoreclr.dylib
...bunch of stuff snipped...
dyld: loaded: /usr/local/share/dotnet/runtime/coreclr/System.Globalization.Native.dylib
```

@davidfowl Is it expected that `dotnet run` would be running against the runtime that comes with the CLI instead of the one listed in pulled in via project.json?  If so, you will need to update the runtime that ships as part of the CLI (and it will not be possible to run with older versions of the packages, either rc2 or rc3 which do not have this name change).

**Comment by davidfowl** [comment]
@ellismg sorry I made to investigate that, it's a known issue being addressed here https://github.com/dotnet/cli/pull/1243

**Comment by tonysneed** [comment]
Looks like you guys are on top of it. :+1:  Is there a workaround at this point?

**Comment by davidfowl** [comment]
It should either be:

```
"NETStandard.Library": "1.0.0-rc2-23805"

OR

"NETStandard.Library": "1.0.0-rc2-23728",
```

**Comment by davidfowl** [comment]
Hold on, that might not be it.

**Comment by ellismg** [comment]
Here's a terrible hack that you can use.  Basically this will update the runtime that is used by the CLI to a newer version.

Change the version of `NETStandard.Library` to `1.0.0-rc2-*`.  Do a `dotnet restore` followed by a `dotnet publish` .  A newer version of the runtime has been published with the app and we can copy things from there.

Change to `/usr/local/share/dotnet/runtime/coreclr/` and then do the following (you'll need update the path  in this command line, so don't just blindly copy and paste):

`sudo find . -exec cp /Users/matell/cli-samples/HelloMvc/bin/Debug/dnxcore50/osx.10.11-x64/{} . \;`

(Obviously you need to update the path to your `dnxcore50/osx.10.11-x64` folder).

With the above, I was then able to `dotnet run` HelloMvc.

I believe you could also work around this issue by moving all the packages references back to versions before we introduced this break, but I'm not sure what versions that will be and I don't know if moving that far back will cause other problems.

Can you give this a whirl and let me know if it works out?

**Comment by tonysneed** [comment]
Thanks @ellismg, I'll give your hack a try and let you know if it works. It will be nice to get past it, so I can play around more with the bits.

**Comment by tonysneed** [comment]
@ellismg Worked like a charm - thanks!  Now `dotnet run` works also for other projects.  FYI, it's OK to keep the netstandard lib version as `"NETStandard.Library": "1.0.0-*"`.

I think `dotnet publish` can also be used as an alternative to `dotnet run`.

```console
~/Source/AspNetCore.RC2/HelloWeb $ dotnet publish
Publishing HelloWeb for DNXCore,Version=v5.0/osx.10.11-x64
Compiling HelloWeb for DNXCore,Version=v5.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:02.6051772

Published to /Users/Tony/Source/AspNetCore.RC2/HelloWeb/bin/Debug/dnxcore50/osx.10.11-x64
Published 1/1 projects successfully
~/Source/AspNetCore.RC2/HelloWeb $ cd bin/Debug/dnxcore50/osx.10.11-x64
~/Source/AspNetCore.RC2/HelloWeb/bin/Debug/dnxcore50/osx.10.11-x64 $ ./HelloWeb
Hosting environment: Production
Application base path: /Users/Tony/Source/AspNetCore.RC2/HelloWeb/bin/Debug/dnxcore50/osx.10.11-x64
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

Cheers.

**Comment by davidfowl** [comment]
We made the fix in the latest CLI. closing this out.

**Comment by tonysneed** [comment]
Thanks! Is the latest CLI available from the Getting Started page?

**Comment by davidfowl** [comment]
Maybe I should leave this open until that is confirmed :smile:  (I'm building from source)

**Comment by ellismg** [comment]
@davidfowl Can you share a link to the fix?

**Comment by davidfowl** [comment]
https://github.com/dotnet/cli/commit/28f35c1cfa37fd2d329e273b4c76433e86a95c05

**Comment by julielerman** [comment]
FWIW (also on OSX, like Tony), with the current bits (just cloned) I kept getting:
 **Can not find runtime target for framework 'DNXCore,Version=v5.0' and RID's osx.10.11-x64.**
in response to dotnet run.
But after changing the  "NETStandard.Library to the more explicit 1.0.0-rc2-* instead of just 1.0.0-*,  I got dotnet run to run.

**Comment by davidfowl** [comment]
@julielerman what CLI version?

/cc @pakrym

**Comment by julielerman** [comment]
.NET Command Line Tools (1.0.0-beta-001528)

i installed that from http://dotnet.github.io/getting-started/ last night to update what I installed previosuly.

I see the installer link on the repo is 1556 so will try that and report back.

Also hope it will resolve the issues I'm having trying to run the HelloMvcAPI sample. the others work fine. If not, I'll let you know what they are.

**Comment by davidfowl** [comment]
Should be fixed a while ago
