### ISSUE TITLE
Restore fails on ubuntu 14.04

### ISSUE THREAD

**Issue by billwert** [aspnet/cli-samples#14]
[restore_fail2.txt](https://github.com/aspnet/cli-samples/files/125784/restore_fail2.txt)

The log has tons of failures like this:
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.httpoverrides/1.0.0-rc2-16166/microsoft.aspnetcore.httpoverrides.1.0.0-rc2-16166.nupkg.
log  : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.iisplatformhandler/1.0.0-rc2-16217/microsoft.aspnetcore.iisplatformhandler.1.0.0-rc2-16217.nupkg'.
An error occurred while sending the request.

if I curl that URL I see it is a redirect. On mac and windows the restore works properly, not sure why it fails here. 

I imagine this finally leads to this: 
error: Unable to load package 'Microsoft.AspNetCore.IISPlatformHandler'.
trace: System.AggregateException: One or more errors occurred. (Unable to load package 'Microsoft.AspNetCore.IISPlatformHandler'.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load package 'Microsoft.AspNetCore.IISPlatformHandler'.
   at NuGet.Protocol.Core.v3.RemoteRepositories.PackageUtilities.<OpenNuspecFromNupkgAsync>d__0.MoveNext()

**Comment by nmschulte** [comment]
I'm having a similar issue, though I don't receive the stack trace like @billwert does.

```
# aptitude show dotnet-nightly
Package: dotnet-nightly                  
New: yes
State: installed
Automatically installed: no
Version: 1.0.1.001252-1
```

**Comment by davidfowl** [comment]
Upgrade the CLI and try again?

**Comment by billwert** [comment]
ah, works for me now after updating. @nmschulte? if it works for you we should close this one.

**Comment by nmschulte** [comment]
@billwert, I've been using the `microsoft/dotnet:latest` Docker image to do my testing (because there are no instructions on building the src), and it hasn't changed in six weeks.  I'm not well versed in Docker, but I think the updated [`rendlelabs/docknet` image and the `docknet` script](https://github.com/rendlelabs/docknet-docker) didn't puke when running `dotnet`: probably safe to close.

```
$ docker run -it microsoft/dotnet:latest
Unable to find image 'microsoft/dotnet:latest' locally
latest: Pulling from microsoft/dotnet
d89e1bee20d9: Pull complete 
9e0bc8a71bde: Pull complete 
27aa681c95e5: Pull complete 
a3ed95caeb02: Pull complete 
81a56d4235fc: Pull complete 
37b228997dc8: Pull complete 
4920b6adeb72: Pull complete 
Digest: sha256:c6a0887f45714b800fa5208234eac091101842a4a210b7dac2a66b7929063081
Status: Downloaded newer image for microsoft/dotnet:latest
root@2f29ad859e4c:/# mkdir hello_world
root@2f29ad859e4c:/# cd hello_world/
root@2f29ad859e4c:/hello_world# dotnet new
dotnet: lttng-ust-comm.c:1446: lttng_ust_init: Assertion `!ret' failed.
Aborted (core dumped)
root@2f29ad859e4c:/hello_world# 
```
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
microsoft/dotnet    latest              66189c9faadd        6 weeks ago         897 MB
```

```
$ docknet new
Unable to find image 'rendlelabs/docknet:latest' locally
latest: Pulling from rendlelabs/docknet
a64038a0eeaa: Pull complete 
2ec6e7edf8a8: Pull complete 
0a5fb6c3c94b: Pull complete 
a3ed95caeb02: Pull complete 
66362e53a0e6: Pull complete 
426f264cd6a5: Pull complete 
Digest: sha256:db3c0446107eec0b56f4f80b6767e563b85267111a8c27172e7f3bdd05921ef0
Status: Downloaded newer image for rendlelabs/docknet:latest
Created new C# project in /tmp/test.
$ 
```

**Comment by davidfowl** [comment]
Does this repro with the latest CLI?

**Comment by nmschulte** [comment]
Using rendlelabs/docknet's latest image, it seems `dotnet new` is failing again:

```
$ date -u
Thu Feb 25 07:26:44 UTC 2016
$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
rendlelabs/docknet   latest              3760e4e823a8        4 hours ago         771.4 MB
```

```
$ docknet new
dotnet: lttng-ust-comm.c:1446: lttng_ust_init: Assertion `!ret' failed.
/usr/local/bin/dotnetproxy: line 3:    12 Aborted                 (core dumped) dotnet $@
```

**Comment by davidfowl** [comment]
What version of the CLI is that docker image using?

**Comment by nmschulte** [comment]
I can't easily tell, becuase `dotnet --version` also blows up when I run it.  The docknet docker image is updated nightly just after the dotnet updates build:

 https://github.com/rendlelabs/docknet-docker#how-often-is-it-updated

So, I think that image is from the same nightly build (see the `$ date -u` and the `4 hours ago` from the comment).

**Comment by nmschulte** [comment]
I figured out how to use Docker;

```
$ docker run --entrypoint=/bin/bash -i -t rendlelabs/docknet
root@cde3f0e771a6:/# dotnet --version
.NET Command Line Tools (1.0.0-dev-001606)

Product Information:
 Version:     1.0.0-dev-001606
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

@davidfowl, it looks like this is resolved for me too; thanks for keeping with it.
