### ISSUE TITLE
Fails on ubuntu - can't find UseIISPlatformHandler 

### ISSUE THREAD

**Issue by billwert** [aspnet/cli-samples#16]
/home/markmil/cli-samples/HelloMvc/Startup.cs(20,17): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseIISPlatformHandler' and no extension method 'UseIISPlatformHandler' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)
/home/markmil/cli-samples/HelloMvc/Program.cs(15,26): error CS1061: 'IWebHostBuilder' does not contain a definition for 'UseIISPlatformHandlerUrl' and no extension method 'UseIISPlatformHandlerUrl' accepting a first argument of type 'IWebHostBuilder' could be found (are you missing a using directive or an assembly reference?)

The errors aren't perhaps super surprising just judging by the API names. :)

**Comment by davidfowl** [comment]
Should work fine. Did restore succeed?

**Comment by davidfowl** [comment]
bump?

**Comment by billwert** [comment]
sorry, got sidetracked with something else. it's all working now.
