### ISSUE TITLE
HelloMvcAPI Still Using Old ActionResult names

### ISSUE THREAD

**Issue by julielerman** [aspnet/cli-samples#17]
dotnet run complains on compilation that it doesn't recognize these types. Did they get removed from aspnetcore.mvc? I can't find them when I search the aspnetcore/mvc repo either.
thanks

**Comment by BrennanConroy** [comment]
I think you're looking for https://github.com/aspnet/Announcements/issues/153

**Comment by julielerman** [comment]
thanks. Did search github but it didn't pick up the announcement. Guess a PR is in order! :)
