### ISSUE TITLE
Which is better: preserveCompilationContext or AddControllersAsServices

### ISSUE THREAD

**Issue by colemickens** [aspnet/cli-samples#19]
https://github.com/aspnet/cli-samples/blob/072933574a50240be5be9630bb912a891ae90724/HelloMvcApi/Startup.cs

```
// Without a call to AddControllersAsServices, this project
// requires ("preserveCompilationContext": true) 
```

Which is "better" and why?

Also, I can move this to Home if it's a more appropriate place.

**Comment by nicolocodev** [comment]
I was wondering the same today and I ended up with this conclusion: Use the [`AddControllersAsServices`](http://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/Extensions/DependencyInjection/MvcCoreMvcBuilderExtensions/#methods) if you want to load your controllers from an external assembly or you want to customize the way they are discovered.
So, "I prefer" to use the `"preserveCompilationContext": true` I mean, the code looks better, IMO, but I don't know how it is resolved by runtime or performance issues, etc :confused:

**Comment by davidfowl** [comment]
Neither is better, it was a point in time thing:

`"preserveCompilationContext": true` is only required for view compilation or any runtime compilation really. 

AddControllersAsServices serves a different purpose.

Anyways, that code is gone, the latest CLI fixes things where it's not required for API sites
