### ISSUE TITLE
MVC sample gives 404

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/cli-samples#29]
Sorry, if this is probably a silly question because I am misunderstanding how it works:
I downloaded the repo and did what the readme tells me. The HelloWeb works fine. For the HelloMvc I get 404 for everything I try.
I started the app in a console with "dotnet run" and it gives me:
"Now listening on: http://localhost:5000
As far as I understand, the app should reply to exactly this URL with the Home view.
The request fails, however, and the console log shows:
"The request path / does not match a supported file type"

What am I missing?

Thanks,
Nicolas

**Comment by cnblogs-dudu** [comment]
Same issue.
```
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[3]
      No actions matched the current request
dbug: Microsoft.AspNetCore.Builder.RouterMiddleware[1]
      Request did not match any routes.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 384.5059ms 404 
```
Use Microsoft.AspNetCore.Mvc 1.0.0-rc2-20270.

**Comment by cnblogs-dudu** [comment]
Fixed it by running `apt-get install dotnet` to get .NET Command Line Tools (1.0.0-beta-001793).
404 occurred when used .NET Command Line Tools (1.0.0-dev-001698) installed by `apt-get install dotnet-nightly`.

**Comment by nicolasr75** [comment]
Tried this again on Win 8 with dotnet 1.0.0-beta-002071 but this fails on 'run' with 'Failed to initialize CoreCLR, HRESULT: 0x80004005' (VC++2015 is installed). I guess this is related to github/dotnet/cli#1827 so I will wait for what's the solution there.

**Comment by miguellira** [comment]
@nicolasr75 Ran into this and other issues on recent CLI builds on OS X. My suggestion is to upgrade to the latest CLI and update the project.json to target `netcoreapp1.0`:

```json
"frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    }
```

**Comment by nicolasr75** [comment]
@miguellira I tried what you suggest and got a little further until I hit the dotnet/cli#2037 error you encountered too. I fixed that by pinning Microsoft.NETCore.App to the version that is created by 'dotnet new', which in my case is 1.0.0-rc2-23930. 
Running the app now looks better until I get
	
    fail: Microsoft.AspNetCore.Server.Kestrel[13]
    Connection id "0HKQPLN41JMPQ": An unhandled exception was thrown by the application.
    Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:

	error CS0041: Unexpected error writing debug information -- 'Unable to cast COM object of type 'System.__ComObject' 
    to interface type 'Microsoft.Cci.ISymUnmanagedWriter5'. This operation failed because the QueryInterface call
    on the COM component for the interface with IID '{DCF7780D-BDE9-45DF-ACFE-21731A32000C}' failed due to the 
    following error: Schnittstelle nicht unterst├╝tzt (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)). 
    at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()

I don't know what to do at this point. Any further idea?

Environment:
Win 10 x64
dotnet cli 2171

**Comment by miguellira** [comment]
Just cloned the latest `cli-samples` on my Windows 10 machine with the latest CLI and I get the same error. So much churn right now it's like walking in a mindfield. Might be worth closing this issue and opening a new one with the exception in the title.

```console
.NET Command Line Tools (1.0.0-beta-002175)

Product Information:
 Version:     1.0.0-beta-002175
 Commit Sha:  429eb93cd9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by colemickens** [comment]
See: https://github.com/dotnet/cli/issues/1488

**Comment by colemickens** [comment]
^ Er, it's a different HRESULT, sorry. May or may not be relevant.

**Comment by miguellira** [comment]
@colemickens It's only relevant in the sense that getting the HelloMvc app in cli-samples to run successfully has been a hit or miss with recent CLI drops.

Probably best to just wait for RC2 and stick whatever works for you now.

**Comment by davidfowl** [comment]
Try it again with the 2184 (latest at time of writing)

**Comment by miguellira** [comment]
@davidfowl By the time I got to it the CLI had upgrade to `1.0.0-beta-002188`. Nevertheless, I was able to restore, build and run the latest HelloMvc sample app without modification on Windows 10 x64 :tada: 

Unfortunately, OS X on the same version didn't fair so well:
```console
FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An internal error occurred.
(Exception from HRESULT: 0x8007054F)
```
Should @nicolasr75 close this issue and/or I open a new one?

**Comment by nicolasr75** [comment]
Yes, works for me now too on fresh Win10 and Win8 with CLI 2188! :tada: 

How do you handle the closing of issues reported by non-Microsoft people? Am I supposed to close it when I find it's solved? Or should we just say "works now" and someone from Microsoft closes it later?

**Comment by davidfowl** [comment]
Doesn't matter. I can close. 

@miguellira open a new one plz
