### ISSUE TITLE
unknown keyword platform 

### ISSUE THREAD

**Issue by spboyer** [aspnet/cli-samples#32]
running `dotnet <command>` and getting `unknown keyword platform` 

Running command:
```
@ ~/projects/spboyer/cli-samples/HelloMvcApi$ (master)
$ dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform
```

CLI Information:
```
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 Runtime Id:  osx.10.10-x64
```

**Comment by spboyer** [comment]
`restore`,`pack`, `build` etc all give same message

**Comment by BrennanConroy** [comment]
Try updating your CLI, that one looks really old

**Comment by spboyer** [comment]
@brennanconroy i just installed from the link on the .io site, probably should use the binaries?

**Comment by yangzhenping** [comment]
Meet this error, too.

```sh
root@ubuntuJumping:/var/aspnet/cli-samples# dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform
root@ubuntuJumping:/var/aspnet/cli-samples# dotnet build
Could not find file '/var/aspnet/cli-samples/project.json'.
root@ubuntuJumping:/var/aspnet/cli-samples# ls
cli-samples.sln  HelloMvc     HelloWeb      ngen-roslyn.ps1  README.md
global.json      HelloMvcApi  HelloWebFull  NuGet.Config
root@ubuntuJumping:/var/aspnet/cli-samples# cd HelloMvc
root@ubuntuJumping:/var/aspnet/cli-samples/HelloMvc# ls
Controllers     Program.cs    Startup.cs  wwwroot
HelloMvc.xproj  project.json  Views
root@ubuntuJumping:/var/aspnet/cli-samples/HelloMvc# dotnet build
unknown keyword platform
root@ubuntuJumping:/var/aspnet/cli-samples/HelloMvc# dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform
root@ubuntuJumping:/var/aspnet/cli-samples/HelloMvc# uname -a
Linux ubuntuJumping 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
I used latest dotnet-cli:apt-get install dotnet=1.0.0.001675-1
BTW, I can run dotnet new, then dotnet restore, and then dotnet run success for a console application.
So I guess there may be something wrong with the project.json file?

**Comment by davidfowl** [comment]
Use this page https://github.com/dotnet/cli#installers-and-binaries to get new CLI bits. The website is grossly out of date.

**Comment by RyzeWu** [comment]
i got the same error.
I just installed the latest .NET Core SDK Installer

dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform

dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by davidfowl** [comment]
Same answer https://github.com/aspnet/cli-samples/issues/32#issuecomment-204740893

**Comment by JamesHinde** [comment]
I get the same error running either dotnet restore or dnu restore with the hellomvc sample.  Both commands work properly in other source directories, so I suspect the problem is in the sample files and not in the command line tools.

**Comment by davidfowl** [comment]
@JamesHinde Did you upgrade to the latest version?

**Comment by ahmad2x4** [comment]
I got the same error. After uninstall and install it works fine

**Comment by gdoron** [comment]
@davidfowl  I installed the new CLI using the new installers in your link.
Still seeing this results:

```
dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

I even unistalled dotnet cli with that version, but it had no affect at all.

**Comment by spboyer** [comment]
@gdoron I would recommend manually removing the current folders before installing. On OSX I have found that the installers do not overwrite the existing files and do not alert you or "fail silently", might also be true on windows.

@davidfowl

**Comment by gdoron** [comment]
@spboyer Thanks for the response!
Which folders to delete?
(Windows)

**Comment by gdoron** [comment]
@spboyer That did it.
Deleted `C:\Program Files\dotnet` and installed again.

@davidfowl

**Comment by gdoron** [comment]
@spboyer It can now run `dotnet restore` and `dotnet run` from the command line.
But in VS I still see errors:
![image](https://cloud.githubusercontent.com/assets/6141009/14430045/a1faee16-0008-11e6-8a9c-11568aa207a0.png)

Do I need to install something else beside the installers in @davidfowl link?

**Comment by GuardRex** [comment]
@gdoron Wait for new tooling when RC2 releases ... VS doesn't work with `dotnet cli` yet.

**Comment by gdoron** [comment]
@GuardRex Ohh, I didn't know that. :disappointed: 
I know there are no dates as of yet, but can you give me a rough estimation of RC2? are we talking about days or weeks? or might be even more?

So if I need to start working on a large project from scratch, should I be using RC1 in the meanwhile?

Thanks.

**Comment by GuardRex** [comment]
@gdoron They said that they would like to release RC2 by the end of this month; however, they also said that April is a target and not a hard and fast deadline. It could slip into May. So ... weeks ... very likely less than four weeks.

I **don't** recommend that you start in RC1. There are so many deltas between RC1 and RC2 and RC2-nightly is fairly stable that I think you should start your project in RC2 and go on the bleeding edge with us nut-cases! :smile: I have four apps in production and all on RC2-nightly bits. I manage the pain ... but keep a pistol handy in case I need to shoot myself :boy: :gun:.

If you need help or have questions with either RC1 or RC2, join us on JabbR, and we'll see if we can help you out. There are a number of excellent devs there familiar with getting things up and running. https://jabbr.net/#/rooms/AspNetCore

**Comment by niemyjski** [comment]
I'm still seeing this with rc2 on appveyor (latest tools). It started happening when I added an asp.net core sample app

https://ci.appveyor.com/project/Exceptionless/exceptionless-net

**Comment by moozzyk** [comment]
Make sure you don't have any pre-preview1 dotnet sdk installed - if you have both rc2 and preview1 rc2 will be used (https://github.com/dotnet/cli/issues/2959)

**Comment by niemyjski** [comment]
It's not, it's all the latest version.. It's a nuget issue error believe it or not.

**Comment by davidfowl** [comment]
@niemyjski I don't see that error message in your build log

**Comment by 9034725985** [comment]
I get the same error on a hello world app using the production dotnet on trusty Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-88-generic x86_64)

```
dotnet-dev/trusty 1.0.0.1451415522-1 amd64
  .NET Core & command line tools
```

Reproduction: 

1. Install dotnet core on trusty 
2. create a new dotnet project 
3. replace project.json  with 

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": { }
  }
}
```

4. run dotnet restore 

Things are also broken on Xenial. 

```
$ ssh kushal@ubuntuserver
kushal@ubuntuserver's password:
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.4.0-28-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

0 packages can be updated.
0 updates are security updates.


Last login: Mon Jun 27 16:22:32 2016 from 192.168.1.10
kushal@ubuntuserver:~$ cat /etc/apt/sources.list.d/dotnetdev.list
deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ xenial main
kushal@ubuntuserver:~$ sudo apt update
[sudo] password for kushal:
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [94.5 kB]
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [224 kB]
Hit:6 https://apt-mo.trafficmanager.net/repos/dotnet xenial InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [220 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [86.3 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [101 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [97.7 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [48.7 kB]
Fetched 966 kB in 0s (1,255 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
kushal@ubuntuserver:~$ sudo apt search dotnet
Sorting... Done
Full Text Search... Done
dotnet-dev-1.0.0-preview2-003093/xenial 1.0.0-preview2-003093-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003096/xenial 1.0.0-preview2-003096-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003098/xenial 1.0.0-preview2-003098-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003100/xenial 1.0.0-preview2-003100-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003102/xenial 1.0.0-preview2-003102-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003104/xenial 1.0.0-preview2-003104-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003109/xenial 1.0.0-preview2-003109-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003112/xenial 1.0.0-preview2-003112-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003116/xenial 1.0.0-preview2-003116-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003118/xenial 1.0.0-preview2-003118-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003119/xenial 1.0.0-preview2-003119-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-dev-1.0.0-preview2-003121/xenial 1.0.0-preview2-003121-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2

dotnet-host/xenial 1.0.2-beta-000547-00-1 amd64
  Microsoft .NET Core 1.0.0 - Host

dotnet-hostfxr-1.0.1/xenial 1.0.1-1 amd64
  Microsoft .NET Core 1.0.0 - Host FX Resolver 1.0.1

dotnet-hostfxr-1.0.2-beta-000547-00/xenial 1.0.2-beta-000547-00-1 amd64
  Microsoft .NET Core 1.0.0 - Host FX Resolver 1.0.2-beta-000547-00

dotnet-sharedframework-microsoft.netcore.app-1.0.0/xenial 1.0.0-1 amd64
  Microsoft .NET Core 1.0.0 - Runtime Microsoft.NETCore.App 1.0.0

dotnet-sharedframework-microsoft.netcore.app-1.0.1-beta-000547-00/xenial 1.0.1-beta-000547-00-1 amd64
  Microsoft .NET Core 1.0.0 - Runtime Microsoft.NETCore.App 1.0.1-beta-000547-00

libgtk-dotnet3.0-cil/xenial 2.99.3-2 amd64
  GTK.NET library

libgtk-dotnet3.0-cil-dev/xenial 2.99.3-2 amd64
  GTK.NET library - development files

libgtk2.0-cil/xenial 2.12.10-6 amd64
  CLI binding for the GTK+ toolkit 2.12

libgtk2.0-cil-dev/xenial 2.12.10-6 amd64
  CLI binding for the GTK+ toolkit 2.12

kushal@ubuntuserver:~$ exit
logout
Connection to ubuntuserver closed.

```

**Comment by bhallaheemanshu** [comment]
Hi guys can anybody please conclude the answer for this error please "Unknown Keyword Platform"

**Comment by BrennanConroy** [comment]
Usually its because you have an old dotnet version that you're using

**Comment by niemyjski** [comment]
My issue was caused by nuget trying to restore project.json references (via nuget restore). I removed nuget restore call and all is well!

**Comment by moozzyk** [comment]
[He seems to be using dnx](https://github.com/aspnet/cli-samples/issues/37#issuecomment-231024109) so it won't work since `platform` was introduced post RC1. Time to upgrade bro.

**Comment by bhallaheemanshu** [comment]
@BrennanConroy @niemyjski @moozzyk 

Thanks yes i was using rc1 , i have upgraded to rc2 now , do anyone have a sample app in rc2 ? can anyone please share it with me at bhallaheemanshu@gmail.com

**Comment by moozzyk** [comment]
The repo you are commenting on has samples. You should also upgrade to rtm since it has already shipped.
