### ISSUE TITLE
Run on IIS

### ISSUE THREAD

**Issue by nojaf** [aspnet/cli-samples#35]
I'm trying to run one of the samples on IIS as described on https://docs.asp.net/en/latest/publishing/iis.html#iis-server-configuration

```
<configuration>
  <system.webServer>
    <aspNetCore forwardWindowsAuthToken="true" processPath="dotnet" arguments="%APPLICATION_PATH%" stdoutLogEnabled="false" stdoutLogFile="logs\stdout.log" startupTimeLimit="3600" />
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
  </system.webServer>
</configuration>
```

I'm guessing IIS has no clue what the aspNetCore element is. What am I missing here?

```
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Detailed Error Information:
Module	   IIS Web Core
Notification	   Unknown
Handler	   Not yet determined
Error Code	   0x8007000d
Config Error	   
Config File	   \\?\C:\Temp\netsite\web.config
Requested URL	   http://localhost:8300/
Physical Path	   
Logon Method	   Not yet determined
Logon User	   Not yet determined

Config Source:
   -1: 
    0: 

More Information:
This error occurs when there is a problem reading the configuration file for the Web server or Web application. In some cases, the event logs may contain more information about what caused this error.
View more information »
```

**Comment by davidfowl** [comment]
> I'm guessing IIS has no clue what the aspNetCore element is. What am I missing here?

https://github.com/aspnet/Announcements/issues/164

**Comment by nojaf** [comment]
Ok, that explains that.
If I do ```dotnet build``` and ```dotnet publish```, it never produces an exe.

So I can't use it in my config as in the announcement.
``` <aspNetCore processPath="..\MySite.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" />```

**Comment by davidfowl** [comment]
Yea, it's not supposed to produce an exe. You run the application by passing in the path to dotnet and the application dll.

**Comment by dougludlow** [comment]
I've done the exact same thing as @nojaf and I'm getting the same 500.19. Can anyone shed more light on how to get this to work?

**Comment by GuardRex** [comment]
@dougludlow Are you following the guidance in https://docs.asp.net/en/latest/publishing/iis.html? See the Common Errors section for "Incorrect server role, module not installed, or incorrect permissions"

**Comment by dougludlow** [comment]
@GuardRex I got it figured out. I didn't have the correct aspnetcoremodule installed. I installed the one listed on aspnet/Announcements#164, but that is outdated now. When I installed the one included with Windows (Server Hosting) installer on https://www.microsoft.com/net/download, I got it working. Thanks!
