### ISSUE TITLE
unknown keyword platform 

### ISSUE THREAD

**Issue by Cuiqs76** [aspnet/cli-samples#37]
Open the "cli-samples"  solution with vs2015.  and raise a error "unknown keyword platform,... ......\HelloMvc\project.json"

**Comment by davidfowl** [comment]
Yeap! VS 2015 doesn't support the new platform keyword.

**Comment by arekbal** [comment]
Same error in CLI.

$ dotnet restore
error: TODO: unknown keyword platform
log  : Restoring packages for F:\PROJECTS\cli-samples\HelloWebFull\project.json...
unknown keyword platform

**Comment by nbilling** [comment]
I am seeing the same issue:
PS C:\Users\nbilling\desktop\HelloMvc> dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform

**Comment by moozzyk** [comment]
what is your `dotnet --info`? This was fixed very recently...

**Comment by nbilling** [comment]
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

I just downloaded this one to a test machine from the dotnet-cli site. Is there a more recent public build?

**Comment by moozzyk** [comment]
This is too old. I am running this: 1.0.0-beta-002256 (which is about a week old).

**Comment by nbilling** [comment]
Thanks, that got me past this error :)
@arekbal If, as I did, you downloaded from the GitHub.io site, you can go to https://github.com/dotnet/cli and get a much more recent build.

**Comment by arekbal** [comment]
I tried these builds yesterday.
Fails to update to newer version or uninstall old... dotnet -v shows all same even after uninstalling all 3 (rerunning the setup files with success)
I talk of Windows here

**Comment by moozzyk** [comment]
@arekbal - did you download the .NET Core SDK Installer from  https://github.com/dotnet/cli ?

**Comment by cnblogs-dudu** [comment]
```bash
wget https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
dpkg -i dotnet-host-ubuntu-x64.latest.deb

wget https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb

wget https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sdk-ubuntu-x64.latest.deb
dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
```

**Comment by arekbal** [comment]
@moozzyk yup
I did it again just for you a moment ago. Same result:

$ dotnet -v
.NET Command Line Tools (1.0.0-beta-001598)

**Comment by nbilling** [comment]
@arekbal I had this same issue trying to install on top of the older installer. What fixed it for me was to manually uninstall all of the dotnet cli related stuff I could find and then reinstall the new "SDK" installer. There seems to be an issue with the new dotnet cli installer build cleaning up the (stable?) beta release one.

**Comment by fcatae** [comment]
After installing the latest version, I had to change the %path% from "C:\Program Files\dotnet\bin" to "C:\Program Files\dotnet". This fixed the problem for me.

**Comment by MrDustpan** [comment]
I was also getting this error on mac os x.  To fix it I removed the old CLI install by deleting the folder "usr/local/share/dotnet" and then installed the latest package from https://github.com/dotnet/cli#installers-and-binaries.

**Comment by San7hos** [comment]
@MrDustpan This helps, I was also stuck while reinstalling, after deleting the folder I could install the newer version

**Comment by GuardRex** [comment]
There is an issue for the problem of -1598 lingering. https://github.com/dotnet/cli/issues/1919

**Comment by huangshan** [comment]
I got this same error on my Windows after I installed the latest version(1.0.0-preview1-002702), I solved it by clean the system path and reinstall. (update C:\Program Files\dotnet\bin to C:\Program Files\dotnet\ may also work)

**Comment by bhallaheemanshu** [comment]
hi devs , I am running command below 
dnx .gen controller ................
dnx gen
dnx ef
(gen and ef are command in projects.json)

`"commands": {
    "ef": "EntityFramework.Commands",
    "gen": "Microsoft.Framework.CodeGeneration"
   
  },`
But it gives error 

"unknown Keyword Platform"

**Comment by moozzyk** [comment]
dnx is not a thing anymore. You need to move `dotnet`.

**Comment by bhallaheemanshu** [comment]
@moozzyk  thanks
