### ISSUE TITLE
Move NuGet.config into the sample projects

### ISSUE THREAD

**Issue by GuardRex** [aspnet/cli-samples#40]
Legacy `NuGet.config` feed combinations will break these apps. It's not readily apparent what the feeds should be when the file is located in the repo in this position. A common use pattern of the samples is that the user downloads the ZIP, decompresses, and pulls the one project they want out of the samples folder and starts working with it.

I'd like to suggest that you consider moving the `NuGet.config` file into each of these four sample projects (five if you agree that a standalone sample should be here, too, https://github.com/aspnet/cli-samples/issues/36). That would make the file discoverable when folks are working with the samples.

**Comment by moozzyk** [comment]
All the samples use the same set of feeds and the general pattern we use across all the repos is that we put NuGet.config in the root of the repo. The NuGet.config itself has the `<clear />` tag to prevent from using feeds specified elsewhere (e.g. globally). I don't think the duplication will help but it will be a burden to maintain. Our CI also depends on the NuGet.config being in the root of the repo (this does not apply to this repo - it's not build by the CI).

**Comment by GuardRex** [comment]
> I don't think the duplication will help

I think it would help only because people would notice the file more easily and it would "travel" a little better when people drag-and-drop one of the projects out of the decompressed assets to some other place to work with the sample (exactly what I've done several times).

What's the greater burden? ... Having a thousand devs ending up with the wrong feeds or just keeping four (or five) little files in these projects. Time will tell.

However, I get you on the factors that led to it being where it is. I'm good.

**Comment by mikes-gh** [comment]
Does nuget.config at the solution level work for dotnet cli or vscode at the project level?

**Comment by GuardRex** [comment]
My solutions are only single projects with a `NuGet.config` for each, so I can't really say myself.
