### ISSUE TITLE
How to create a web application by dotnet?

### ISSUE THREAD

**Issue by Brian-Ding** [aspnet/cli-samples#41]
i can use "dotnet new" to create a console app, but how to do so for a web application?

**Comment by kerryjiang** [comment]
For now, you need add required dependencies and other nodes in project.json, and add some lines of code which are required by asp.net core manually.
The sample projects in the below repository should be able to work with the latest dotnet cli:
[https://github.com/kerryjiang/dotnetcore-samples/tree/master/mvc](https://github.com/kerryjiang/dotnetcore-samples/tree/master/mvc)

**Comment by Brian-Ding** [comment]
@kerryjiang Thank you for you answer! Very helpful samples in your repository
