### ISSUE TITLE
Cannot restore HellowWebApi dependencies on dotnet 1.0.0-rc2-002392

### ISSUE THREAD

**Issue by cleftheris** [aspnet/cli-samples#43]
When I restore I get the following errors 

Unable to resolve 'Microsoft.Extensions.DependencyModel (>= 1.0.0-rc2-002392)'

>Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json

**Comment by maxonico** [comment]
Same problem here.

**Comment by cleftheris** [comment]
I fixed it by adding an extra feed to the nuget.config located in the repository root folder (cli-samples). Just add "https://dotnet.myget.org/F/cli-deps/api/v3/index.json" and retry. Check out the pull request https://github.com/aspnet/cli-samples/pull/44

**Comment by maxonico** [comment]
The result of adding that feed in the NuGet.config file is this:

> info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-cor
> e/nuget/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/index.json 2826ms
> error: Package Microsoft.Extensions.DependencyModel 1.0.0-beta-001584 is not com
> patible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensi
> ons.DependencyModel 1.0.0-beta-001584 supports:
> error:   - dnxcore50 (DNXCore,Version=v5.0)

Not having that feed gives me this:

>     Unable to resolve 'Microsoft.AspNetCore.Mvc.Formatters.Json (>= 1.0.0)' for
> '.NETCoreApp,Version=v1.0'.
>     Unable to resolve 'Microsoft.AspNetCore.Mvc.Core (>= 1.0.0)' for '.NETCoreAp
> p,Version=v1.0'.
>     Unable to resolve 'Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0)' for '.NET
> CoreApp,Version=v1.0'.

**Comment by cleftheris** [comment]
Maybe it has something todo with the order of the feeds. Did you add it first on the list?

**Comment by maxonico** [comment]
Yep, but still failing.

> 'Microsoft.AspNetCore.Server.IISIntegration (>= 1.0.0)'

I have a brand new "cli-samples" folder, added the NuGet.config file and added to the file the feed you suggested. Although the error changed, there's still a missing dependency.

This is the NuGet file:

`<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />    
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />        
    <add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />`

and this the project.json:

`"dependencies": {
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-23931"
    },
    "System.Runtime.Serialization.Primitives": "4.1.1-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+wp80+win8+wpa81+dnxcore50"
      ]
    }
  },`

**Comment by cleftheris** [comment]
this is exactly as I did. Although I restored through command-line using `dotnet restore`. Other than that I cannot see what I did to fix it.

I will try to ping someone on twitter about it and see what happens.

**Comment by maxonico** [comment]
Yes, in fact, I was working fine but then I started to add SSL to Kestrel, 

> "Microsoft.AspNetCore.Server.Kestrel.Https": "1.0.0-*",

`x.UseHttps("cert.pfx", "pass");`

but because of the change in the project.json I had to make a `dotnet restore`. After that restore, I started the get the error.

**Comment by maxonico** [comment]
Well, adding this feed:

`<add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />`

did the trick for me.

Took from: [Feed](https://myget.org/gallery/aspnetcidev)

**Comment by cleftheris** [comment]
Bleeeeeding edge :)

**Comment by pranavkm** [comment]
Sorry about the issue. I issued a publish to aspnetcirelease last night for a build with incorrect dependencies. Redoing the build now which should fix it.

**Comment by pranavkm** [comment]
Should be fixed now. Let me know if you're still seeing issues here.

**Comment by IRooc** [comment]
Hi I just cloned the cli-samples repo and and updated the NuGet.Config to 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />

	<add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
	<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 
	<add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" /> 
	<add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

When I do dotnet restore on the HelloWeb project it seems to work but dotnet run it shows this output:
```
W:\cli-samples\HelloWeb>dotnet run
Project HelloWeb (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
The structure of init data has changed, do not know how to interpret it
```

Any ideas?

**Comment by pranavkm** [comment]
What does `dotnet --version` say?

**Comment by IRooc** [comment]
W:\cli-samples\HelloWeb>dotnet --version
1.0.0-rc2-002395

**Comment by pranavkm** [comment]
From: https://github.com/dotnet/cli/issues/2194#issuecomment-210504839, try wiping the cli directory (%LocalAppData%\Microsoft\dotnet\cli) and retrying.

**Comment by IRooc** [comment]
I dont have a dotnet folder in %LocalAppData%\Microsoft\

I removed all files from %LocalAppData%\NuGet\v3-cache as well and did a restore and tried run, with same result

**Comment by IRooc** [comment]
code shows this output on "debug start"
```
The structure of init data has changed, do not know how to interpret it

The program 'w:\cli-samples\HelloWeb\bin\Debug\netcoreapp1.0\HelloWeb.dll' has exited with code 148 (0x00000094).
```

**Comment by moozzyk** [comment]
@IRooc - you NuGet.config will cause issues. Decide if you want to use release or dev branch and leave only
```
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
```

or 

```
    <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
``` 
feeds. 

For the `The structure of init data has changed,...` - as per https://github.com/dotnet/cli/issues/2194#issuecomment-210504839 I think you need to remove previous versions of dotnet you have installed.

**Comment by IRooc** [comment]
@moozzyk Hi I only have the lastest dotnet cli installed:

```
W:\cli-samples\HelloWeb>where /R c:\ dotnet.exe
c:\Program Files\dotnet\dotnet.exe
c:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-23931\dotnet.exe
c:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002339\dotnet.exe
c:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002395\dotnet.exe
```

The shared onces were installed by dotnet itself I think, no other places where i have a dotnet.exe.

The NuGet.Config is now
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />    
	
	<add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />

	<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 
	<add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />
  </packageSources>
</configuration>

```

The dotnet restore works, but the dotnet run still fails with 
```
The structure of init data has changed, do not know how to interpret it
```

**Comment by IRooc** [comment]
Sorry Ignore that, in Program Files uninstalled old dotnet.exe packages
Now I only have one 
```
W:\cli-samples\HelloWeb>where /R c:\ dotnet.exe
c:\Program Files\dotnet\dotnet.exe
c:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002395\dotnet.exe
```
and it works! Thank you very much!

**Comment by moozzyk** [comment]
You had 3 shared runtimes: 
shared\Microsoft.NETCore.App\1.0.0-rc2-23931\dotnet.exe
shared\Microsoft.NETCore.App\1.0.0-rc2-3002339\dotnet.exe
shared\Microsoft.NETCore.App\1.0.0-rc2-3002395\dotnet.exe

Remove these feeds: 
```
  <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 
  <add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />
```

You should not need them. If there are newer versions of packages on these feeds that are incompatible with what ASP.NET is using you will end up in a NuGet Hell. All packages that ASP.NET needs are duplicated to aspnetci{branch} feeds.

**Comment by IRooc** [comment]
Done and still works thanks again!

**Comment by cleftheris** [comment]
Thanks everyone. Sorry for the late response but I am in a different time zone. Always to early or to late to the party ☺ UTC+2. Have a nice weekend
