### ISSUE TITLE
Cannot debug HelloWeb

### ISSUE THREAD

**Issue by germansak** [aspnet/cli-samples#45]
Followed step-by-step from video "ASP.NET Community Standup - April 12th, 2016 - The Quickening"
When I try to debug app it says: 

_No executable found matching command "dotnet-c:\Users\germansak\DotNetCore"
The program 'c:\Users\germansak\DotNetCore Projects\cli-samples\HelloWeb\bin\Debug\netcoreapp1.0\HelloWeb.dll' has exited with code 1 (0x00000001)._

**Comment by germansak** [comment]
Nevermind. It's the issue with spaces on the path. Moved to a spaceless path and it worked!!
Thanks anyway

**Comment by paenl** [comment]
easy fix would be spaceless path, this still needs to be resolved as its internal
