### ISSUE TITLE
error: TODO: unknown keyword platform on OSX

### ISSUE THREAD

**Issue by mountain65** [aspnet/cli-samples#49]
Cloned the recent version of the code, did `dotnet restore` and got (among other things) the following error:
error: TODO: unknown keyword platform

**Comment by BrennanConroy** [comment]
What version of the dotnet cli?

**Comment by mountain65** [comment]
Sorry, that is on version 
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

**Comment by mountain65** [comment]
And that's the latest version I can get on http://dotnet.github.io/getting-started/

**Comment by davidfowl** [comment]
Don't use that, read the link on the README.md in this repository.

**Comment by mountain65** [comment]
Sorry, my bad. I recognised the link and thought "Been there, seen that, done that". But installing the rc2 initially gave me the same version number for the dotnet cli. After removing the /usr/local/share/dotnet directory and reinstall the latest.pkg I had the rc2.

Works like a charm now!
Sorry for wasting your time.
