### ISSUE TITLE
Project.json and Global.json for .Net 4 Framework Apps

### ISSUE THREAD

**Issue by ndglover** [aspnet/cli-samples#5]
I'm using {ProjectName}.project.json in my WPF apps to seperate external dependencies away from .csproj. I'd love to have global.json work so that packages can be swapped out for source code just like it works today with dnu, dnx. 

Would this be possible with the new cli toolset? I assume it would probably require changes to msbuild right now to work from visual studio?

**Comment by davidfowl** [comment]
Please file an issue on hub.com/dotnet/cli
