### ISSUE TITLE
Unknown keyword platform

### ISSUE THREAD

**Issue by takazm** [aspnet/cli-samples#56]
I have installed the recently release CORE R2 Tooling and created a new project. An attempt to restore packages fails with the above given error.
Here the command: dotnet restore
error: TODO: unknown keyword platform
unknown keyword platform

Any reason why this is happening

**Comment by moozzyk** [comment]
Make sure you removed all the old versions of dotnet you have on your machine. I saw a [case](https://github.com/aspnet/PlatformAbstractions/issues/40) where a very old version of dotnet was invoked even though they installed the latest one. I think `where.exe dotnet` should help you find the executable you are running.

**Comment by GuardRex** [comment]
Happened here, too ... https://github.com/dotnet/cli/issues/2948

**Comment by bhallaheemanshu** [comment]
Hi @GuardRex , I am also getting "unknown keyword platform" error Can you please tell what is exact problem with this error

**Comment by GuardRex** [comment]
@bhallaheemanshu You figured it out from the answers on the other issue, correct? Very old bits often must be manually removed. I had my own little battle with having to do that once: https://github.com/dotnet/cli/issues/2948

**Comment by bhallaheemanshu** [comment]
@GuardRex yes i got it thanks
