### ISSUE TITLE
xproj files are still for dnx

### ISSUE THREAD

**Issue by zygimantas** [aspnet/cli-samples#57]
xproj files (at least cli-samples/HelloMvcApi/HelloMvcApi.xproj) is still for dnx and not for cli.

**Comment by zygimantas** [comment]
title changed

**Comment by zygimantas** [comment]
By the way, is it still possible to move bin and obj to the outside of the project folder or is it not recommended for cli?

**Comment by davidfowl** [comment]
Not recommended currently

**Comment by derwasp** [comment]
@davidfowl is there a ticket I can track about allowing `./artifacts/` folder outside project folder?
