### ISSUE TITLE
dnu Error: unknown keyword platform

### ISSUE THREAD

**Issue by AndrewKralovec** [aspnet/cli-samples#59]
Hello, i was trying to install the MongoDb driver, and i noticed any time I ran the dnu command, I get an Unknown keyword platform. I also get this error for all other dnu commands. Does anyone have a fix and/or reason why this is happening? 

```
andrew@andrew-PC:~/workspace/CSharp/LinuxASP/First$ dnu install MongoDb.Driver
Microsoft .NET Development Utility Mono-x64-1.0.0-rc1-16609

  CACHE https://api.nuget.org/v3/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/mongodb.driver/index.json
Error: unknown keyword platform
andrew@andrew-PC:~/workspace/CSharp/LinuxASP/First$ 
```
Version 

```
andrew@andrew-PC:~/workspace/CSharp/LinuxASP/First$ dotnet --version
1.0.0-preview1-002702
```

List

```
andrew@andrew-PC:~/workspace/CSharp/LinuxASP/First$ dnvm list
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-update1    coreclr x64          linux           
       1.0.0-rc1-update1    mono                 linux/osx       
  *    1.0.0-rc1-update2    mono                 linux/osx       default

```

**Comment by moozzyk** [comment]
dnx/dnu/dnvm don't work with RC2 you need to move to dotnet. See: https://github.com/aspnet/Announcements/issues/176

**Comment by AndrewKralovec** [comment]
Awsome thanks, that was really fast. dotnet doesn’t have an install option. How do i install packages via Nuget?

**Comment by moozzyk** [comment]
https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/ will be first stop. From here http://dot.net you can install command line tools or, if you want to use VS install VS web tooling which will install everything you need.

**Comment by AndrewKralovec** [comment]
Thanks. Could you supply me with  the CLI dotnet repo. I'm the lazy type and ill just code an install option.

**Comment by moozzyk** [comment]
you can download an msi from http://dot.net. The cli repo is here https://github.com/dotnet/cli.

**Comment by AndrewKralovec** [comment]
You are my new god. I really appreciate the help, thanks!

**Comment by AndrewKralovec** [comment]
I'm really sorry to keep bugging you. I have been reading the documentation and I'm kinda confused on where to add an third party dependency. 

I tried adding the mongoDb driver to the project.json  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "mongocsharpdriver": "1.10.0-rc0",
      "type": "platform"
    },However this leads to errors whenever I try using using MongoDB.Driver;/home/andrew/workspace/CSharp/LinuxASP/First/Controllers/HomeController.cs(6,7): error CS0246: The type or namespace name 'MongoDB' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:06.9669704 
Where should i place the MongoDb Driver in project.json? Thank you very much for your time. If you could either point me in the right direction or know of a solution, i would greatly appreciate it. Please do not hesitate to email or call me if you have any questions or need any additional information, thanks again.

**Comment by GuardRex** [comment]
@AndrewKralovec There are three main sets of docs:
- https://docs.asp.net/en/latest/
- http://dotnet.github.io/docs/
- http://ef.readthedocs.io/en/latest/

If you have questions, it's best to hit up the devs on Slack: http://tattoocoder.com/aspnet-slack-sign-up/
