### ISSUE TITLE
Give WebHostBuilder.UseEnvironment examples 

### ISSUE THREAD

**Issue by roydukkey** [aspnet/cli-samples#6]
Show how `WebHostBuilder.UseEnvironment()` can be affect by Visual Studio configurations and compiler directives.

**Comment by davidfowl** [comment]
> Show how WebHostBuilder.UseEnvironment() can be affect by Visual Studio configurations and compiler directives.

What do you mean? Those are 2 different features. Environment is runtime, compiler directives are well compile time. You can ifdef and UseEnvironment or use whatever logic you like to specify the environment.

**Comment by roydukkey** [comment]
Okay. So maybe compiler directives don't make sense then. But, shouldn't/couldn't VS configuration profiles trigger this change, so that when "Start with Debugging" would pull the environment suggestion from the configuration profile?

**Comment by zhouyongtao** [comment]
LZ 是中国人，国内关注CLI 的少啊，新年好。
