### ISSUE TITLE
Test Web bind on specified IP and Port

### ISSUE THREAD

**Issue by sujunmin** [aspnet/cli-samples#60]
In order to bind the test web on specified IP and Port, modify the Program.cs to do that.

#58

**Comment by GuardRex** [comment]
Why is this needed? The default applies: https://github.com/aspnet/Hosting/blob/e7b8c3f90a781a55658b4245571c5bf5dac5e56e/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L50

Side ?: Why is `.UseContentRoot(Directory.GetCurrentDirectory())` needed? That defaults as well: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L237

For the optional configs, shouldn't the docs explain them? Samples probably should imply what is sufficient for an app to run, not list every possible config setting with default values.

**Comment by GuardRex** [comment]
Why is this needed? The default applies: https://github.com/aspnet/Hosting/blob/e7b8c3f90a781a55658b4245571c5bf5dac5e56e/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L50

Side ?: Why is `.UseContentRoot(Directory.GetCurrentDirectory())` needed? That defaults as well: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L237

For the optional configs, shouldn't the docs explain them? Samples probably should imply what is sufficient for an app to run, not list every possible config setting with default values.

**Comment by GuardRex** [comment]
[Github is having trouble this morning. I post and Preview shows the post but it doesn't appear here. If I post again here, it double-posts here. I think a problem they had at 10am CST has resulted in some kind of concurrency issue in their dB. This post I'm making might show up twice here.]

Why is this needed? The default applies: https://github.com/aspnet/Hosting/blob/e7b8c3f90a781a55658b4245571c5bf5dac5e56e/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L50

Side ?: Why is `.UseContentRoot(Directory.GetCurrentDirectory())` needed? That defaults as well: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L237

For the optional configs, shouldn't the docs explain them? Samples probably should imply what is sufficient for an app to run, not list every possible config setting with default values.

**Comment by sujunmin** [comment]
Yes, the default setting is not need to set, but if you want to change the
test web bound on specified IP and port (when I run this sample in the
microsoft/dotnet:latest docker container, it is no easy way to connect the
container for localhost:5000 easily), so it needs some way to set web
server in specified IP and port.
2016年5月23日 23:17於 "Luke Latham" <notifications@github.com>寫道：

**Comment by GuardRex** [comment]
My point was simply that docs will catch up. If the sample is changed here, then everyone will think that they need to make this setting. I think the same is true for the content root.

[btw-- I'm having the same GH problem you're having. Posts don't show up after I make them. So I won't double-post again and just hope for the best! :smile: )

**Comment by sujunmin** [comment]
Yes, but I think some guys to use this sample could change this settings to connect the test web easily.
Or I should comment it out for someone needed?

I got stuck for GH, too.

**Comment by GuardRex** [comment]
I think what is needed is either or both: (1) A dedicated sample for .NET Core in Docker, (2) a document like "ASP.NET Core with Docker" in the tutorials area perhaps: https://docs.asp.net/en/latest/tutorials/index.html

One thing you (or someone) could do is provide an un-official document on this at Slack. There is a #docker channel at Slack. They have one Pinned Item there that leads to https://hub.docker.com/r/microsoft/dotnet/, but that doesn't look too good.

If you visit the #iis channel, you'll see I'm developing an IIS un-official doc to cover a lot of stuff in one place that will be helpful for IIS folks. Perhaps, the #docker channel should have something similar.

btw- If you aren't on Slack, here's the link: http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by sujunmin** [comment]
So you think it is no need to change sample code, and need to describe it in documents, right?

**Comment by GuardRex** [comment]
I think that is correct. If the samples come to have these settings, it will defeat the purpose of even having defaults. Everyone will start putting defaults into code not knowing what is required and what isn't.

You can ask the docs team about where/how the requirement for `.UseUrls()` should be documented for Docker over in the Docs repo and see what they say: https://github.com/aspnet/Docs/issues

As it stands today, I don't see a good MS document on Docker, but I also haven't looked around too much.

**Comment by sujunmin** [comment]
Ok, I will close this issue and cancel this pr, thanks.

**Comment by GuardRex** [comment]
@sujunmin A #docker channel :cat:, @mikeharder, at Slack commented on this. He said more info on this can be found here: https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-troubleshooting-docker-errors/

**Comment by sujunmin** [comment]
Yes! That is what I want to represent, thank you @GuardRex .
Maybe this can be list in Readme. md?

**Comment by GuardRex** [comment]
That's up to @davidfowl ... who is :eyes: watching.
