### ISSUE TITLE
Publishing to tilde/foo on Linux

### ISSUE THREAD

**Issue by vkichline** [aspnet/cli-samples#62]
With RC2 on Cinnamon Mint, running the command:
`dotnet publish --output "~/pub"`
created a ~ directory containing pub, rather than creating pub in my home directory.

**Comment by moozzyk** [comment]
@vkichline - this belongs to dotnet. Can you file this here: https://github.com/dotnet/cli/issues?

**Comment by vkichline** [comment]
Done: #3438

**Comment by moozzyk** [comment]
Thank you!
