### ISSUE TITLE
Unable to load service index for source...

### ISSUE THREAD

**Issue by aapis** [aspnet/cli-samples#63]
Not sure where this issue belongs, but you can see what I did below and it did not work as expected.  The initial [hello world app](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/) works fine, and openssl has been linked properly.  Not sure what else to try?

```shell
prieber@~/Personal$ git clone git@github.com:aspnet/cli-samples.git dotnet-cli-samples
Cloning into 'dotnet-cli-samples'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: Counting objects: 684, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 684 (delta 3), reused 0 (delta 0), pack-reused 674
Receiving objects: 100% (684/684), 93.87 KiB | 0 bytes/s, done.
Resolving deltas: 100% (426/426), done.
Checking connectivity... done.
prieber@~/Personal$ cd dotnet-cli-samples/
prieber@~/Personal/dotnet-cli-samples$ dotnet restore
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloMvcApi/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloMvc/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloWebFull/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloWeb/project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't connect to server
```

```shell
$ dotnet --info

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by moozzyk** [comment]
Looks like a NuGet issue: https://github.com/NuGet/Home/issues/2530. [This thread](https://github.com/dotnet/cli/issues/2543) suggests you may need to update openssl on your Mac (https://github.com/dotnet/cli/issues/2543#issuecomment-222170909)

**Comment by aapis** [comment]
`Warning: openssl-1.0.2h_1 already installed`

Would if I could.  That's the latest I can get from brew, but maybe it requires an even newer one?

**Comment by moozzyk** [comment]
I have the same version and don't see this problem. @yishaigalatzer @emgarten - can you take a look?

**Comment by aapis** [comment]
Enabled verbose output, same issue but this might help diagnose the problem.

[dotnet_error.txt](https://github.com/aspnet/cli-samples/files/340253/dotnet_error.txt)

**Comment by moozzyk** [comment]
Not sure if it applies but I just got this error on Ubuntu and the reason was that I did not have libcurl3 installed.

**Comment by aapis** [comment]
Good to know, unfortunately I'm not sure how to get that on OSX.  I tried upgrading curl itself in the hope that it would install libcurl3, latest is 7.49.1 (7.43.0 provided natively), but that did not fix it.

**Comment by moozzyk** [comment]
I am running 7.43 on my Mac and don't see the problem so it must be something different. Since this is a problem with dotnet tooling (I guess you will see this regardless of a project you would try to restore) I would recommend filing this bug in the https://github.com/dotnet/cli repo.

**Comment by aapis** [comment]
Yeah, that seems to be the issue here.  Thanks!
